version: "3"
tasks:
  openapi-generator:
    internal: true
    cmds:
      - docker run --rm -it --name openapi-generator -u $(id -u ${USER}):$(id -g ${USER}) -v ${PWD}:/local --workdir /local openapitools/openapi-generator-cli {{.ARGS}}
    interactive: true

  openapi-generator-cli:
    desc: allow to call openapi-generator-cli directly by passing arguments after `--` (eg. `task openapi-generator-cli -- help`)
    cmds:
      - task: openapi-generator
        vars:
          ARGS: "{{ .CLI_ARGS }}"

  openapi-generator:generate:
    internal: true
    cmds:
      - rm -rf build/{{.LANG}}
      - task: openapi-generator
        vars:
          # `batch` is less verbose than `generate` (less warning and info logged) but allow to groug into one config file
          # ARGS: "generate -i spec/openapi.yaml -g {{.LANG}} -o build/{{.LANG}} --global-property models,modelDocs=false,generateAliasAsModel=true"
          ARGS: "generate --config openapi-generator.conf.d/{{.LANG}}.yaml"
          # ARGS: "batch --fail-fast --verbose openapi-generator.conf.d/{{.LANG}}.yaml"
    sources:
      - spec/**.yaml
    generates:
      - build/{{.LANG}}/**

  ci:
    cmds:
      - task: validate
      - task: codegen

  validate:
    cmds:
      - task: openapi-generator
        vars:
          ARGS: "validate -i spec/openapi.yaml"
          # ARGS: "help validate"

  codegen:
    cmds:
      - task: codegen:java
      - task: codegen:go
      - task: codegen:markdown
      - task: codegen:python
      - task: codegen:rust

  codegen:go:
    cmds:
      - task: openapi-generator:generate
        vars:
          LANG: go

  codegen:java:
    cmds:
      - task: openapi-generator:generate
        vars:
          LANG: java

  codegen:markdown:
    cmds:
      - task: openapi-generator:generate
        vars:
          LANG: markdown

  codegen:python:
    cmds:
      - task: openapi-generator:generate
        vars:
          LANG: python

  codegen:rust:
    cmds:
      - task: openapi-generator:generate
        vars:
          LANG: rust
