version: "3"
tasks:
  openapi-generator:
    internal: true
    cmds:
      - docker run --rm -it --name openapi-generator -u $(id -u ${USER}):$(id -g ${USER}) -v ${PWD}:/local --workdir /local openapitools/openapi-generator-cli {{.ARGS}}
    interactive: true

  openapi-generator-cli:
    desc: allow to call openapi-generator-cli directly by passing arguments after `--` (eg. `task openapi-generator-cli -- help`)
    cmds:
      - task: openapi-generator
        vars:
          ARGS: "{{ .CLI_ARGS }}"

  ci:
    cmds:
      - task: validate
      - task: codegen:rust

  validate:
    cmds:
      - task: openapi-generator
        vars:
          ARGS: "validate -i spec/openapi.yaml"
          # ARGS: "help validate"

  codegen:rust:
    cmds:
      - rm -rf build/rust
      - task: openapi-generator
        vars:
          # `batch` is less verbose than `generate` (less warning and info logged) but allow to groug into one config file
          # ARGS: "generate -i spec/openapi.yaml -g rust -o build/rust --global-property models,modelDocs=false,generateAliasAsModel=true"
          ARGS: "generate --config rust.conf.yaml"
          # ARGS: "batch --fail-fast --verbose rust.conf.yaml"
    sources:
      - spec/**.yaml
    generates:
      - build/rust/**

  codegen:markdown:
    cmds:
      - rm -rf build/markdown
      - task: openapi-generator
        vars:
          ARGS: "generate -i spec/openapi.yaml -g markdown -o build/markdown --global-property models,modelDocs=false,generateAliasAsModel=true"
    sources:
      - spec/**.yaml
    generates:
      - build/markdown/**
